### ISSUE TITLE
feat: more logging output

### ISSUE THREAD

**Issue by attila-lendvai** [rndlabs/swarm-tools-rs#10]
i've started up a

```
$ nice -n20 swarm-tools overlay auto-mine -n4
Mining 4 addresses...
```

and it's just sitting there for minutes, **without any CPU activity**. i have no idea what's happening, and whether to just wait for it. if the latter, then how long? minutes? hours? days?

please help us lost souls with a bit more output! :)

**Comment by attila-lendvai** [comment]
my gnosis node is running as:

```
/gnu/store/sp8gkhcz59z00i6wbqap1hyi8hcjwhm1-nethermind-binary-1.19.2/bin/Nethermind.Runner \
--Sync.TuneDbMode=HeavyWrite --Sync.FastSync=true --Network.EnableUPnP=true \
--JsonRpc.JwtSecretFile=/var/lib/nethermind/jwt-secret --JsonRpc.EnginePort=8551 \
--JsonRpc.EngineHost=localhost --JsonRpc.Port=8545 --JsonRpc.Host=localhost \
--JsonRpc.Enabled=true --Init.WebSocketsEnabled=true --Init.LogFileName=gnosis-e.log \
--Init.LogDirectory=/var/log/nethermind --datadir=/var/lib/nethermind/gnosis-e --config=gnosis
```

**Comment by mfw78** [comment]
It's not really possible to indicate exactly how much time it will take to mine an address, as this depends on:

1. `auto-mine` will seek a storage radius from which to mine (deterministic).
2. The speed at which mining an address happens depends on the CPU / architecture on which the miner is running.
3. The "luck" as it is essentially random, so at worst case, the miner would have to exhaust all the searchable space, at the best case, it gets lucky on the first guess.

I'm going to close this issue in lieu of #11

**Comment by attila-lendvai** [comment]
what i suspect is that it's stuck when communicating with the gnosis node, and as such i'd like more logging regarding e.g. that communication line, not estimating the time mining will take.

that way the last log line could be a hint of where the process gets stuck.
